### ISSUE TITLE
Dropdown is not displayed inside Modal / ActionSheet component

### ISSUE THREAD

**Issue by davidivad96** [onmotion/react-native-autocomplete-dropdown#94] opened 2023-09-10 17:42 UTC
When the `AutocompleteDropdown` is rendered inside a Modal / ActionSheet, the suggestions dropdown is not displayed at all. I've tried setting `zIndex` prop but it seems that's not the problem. Looks like the dropdown menu doesn't receive the trigger to be showed.

I'm using NativeBase components, if that has something to do.

**Comment by vegulla001** [comment] 2023-09-19 10:25
Same here.

**Comment by vegulla001** [comment] 2023-09-19 10:25
Any Solution?

**Comment by davidivad96** [comment] 2023-09-19 10:32
I didn't find any solution, so I ended up using https://github.com/byteburgers/react-native-autocomplete-input instead

**Comment by vegulla001** [comment] 2023-09-20 06:02
I found the solution and that is you must include the flex : 1 in the top view container.

**Comment by vegulla001** [comment] 2023-09-20 06:04
Inside Modal there must be a parent view, for that view  , you must include the flex : 1

**Comment by vegulla001** [comment] 2023-09-20 06:05
@davidivad96 After the solution is worked you can close the issue.

**Closed** 2023-09-20 06:31 UTC

**Comment by navignaw** [comment] 2023-10-27 21:35
@vegulla001 I'm not sure how you got it working with `flex: 1`, can you elaborate or provide a code sample?

From my own debugging, I believe the root cause is because the provider renders the content adjacent to the children: https://github.com/onmotion/react-native-autocomplete-dropdown/blob/main/src/AutocompleteDropdownContext.tsx#L114-L130

This means that if you put the provider at the root level of your app (as recommended by the README), the dropdown list will be mounted all the way at that root level. This means that it will show up underneath the React Native modal.

One workaround we found was to add another provider inside the modal:
```tsx
<Modal animationType="slide" visible={modalVisible}>
  <AutocompleteDropdownContextProvider>
    {children}
  </AutocompleteDropdownContextProvider>
</Modal>
```

There are still some minor issues however where the absolute positioning doesn't quite line up with gestures (swipping down on the modal), but it at least shows up.

**Comment by Tpleme** [comment] 2023-10-29 14:33
Hello, i was experiencing the same problem and thanks to @navignaw comment i got an idea.

I am using react-native-paper Dialog for the Modal, and i fixed this issue by rearranging the order of the providers, so `<AutocompleteDropdownContextProvider>` is a parent of `<PaperProvider />`, instead of the other way around. 

I don't know if this will help someone, but here it is.

**Comment by soroshzzz26** [comment] 2023-11-01 11:13
> Hello, i was experiencing the same problem and thanks to @navignaw comment i got an idea.
> 
> I am using react-native-paper Dialog for the Modal, and i fixed this issue by rearranging the order of the providers, so `<AutocompleteDropdownContextProvider>` is a parent of `<PaperProvider />`, instead of the other way around.
> 
> I don't know if this will help someone, but here it is.

thanks its working

**Comment by p-t10a** [comment] 2024-01-21 13:46
In the case of Android, the list does not appear when used on top of the modal.
I am using the modal of Native Base.
By calling the provider at the top of App.tsx, the list is displayed even on top of the modal in iOS, but it does not appear in Android.
How can this be resolved?

**Comment by vegulla001** [comment] 2024-01-21 17:18
> @vegulla001 I'm not sure how you got it working with `flex: 1`, can you elaborate or provide a code sample?
> 
> From my own debugging, I believe the root cause is because the provider renders the content adjacent to the children: https://github.com/onmotion/react-native-autocomplete-dropdown/blob/main/src/AutocompleteDropdownContext.tsx#L114-L130
> 
> This means that if you put the provider at the root level of your app (as recommended by the README), the dropdown list will be mounted all the way at that root level. This means that it will show up underneath the React Native modal.
> 
> One workaround we found was to add another provider inside the modal:
> 
> ```tsx
> <Modal animationType="slide" visible={modalVisible}>
>   <AutocompleteDropdownContextProvider>
>     {children}
>   </AutocompleteDropdownContextProvider>
> </Modal>
> ```
> 
> There are still some minor issues however where the absolute positioning doesn't quite line up with gestures (swipping down on the modal), but it at least shows up.



> @vegulla001 I'm not sure how you got it working with `flex: 1`, can you elaborate or provide a code sample?
> 
> From my own debugging, I believe the root cause is because the provider renders the content adjacent to the children: https://github.com/onmotion/react-native-autocomplete-dropdown/blob/main/src/AutocompleteDropdownContext.tsx#L114-L130
> 
> This means that if you put the provider at the root level of your app (as recommended by the README), the dropdown list will be mounted all the way at that root level. This means that it will show up underneath the React Native modal.
> 
> One workaround we found was to add another provider inside the modal:
> 
> ```tsx
> <Modal animationType="slide" visible={modalVisible}>
>   <AutocompleteDropdownContextProvider>
>     {children}
>   </AutocompleteDropdownContextProvider>
> </Modal>
> ```
> 
> There are still some minor issues however where the absolute positioning doesn't quite line up with gestures (swipping down on the modal), but it at least shows up.



> @vegulla001 I'm not sure how you got it working with `flex: 1`, can you elaborate or provide a code sample?
> 
> From my own debugging, I believe the root cause is because the provider renders the content adjacent to the children: https://github.com/onmotion/react-native-autocomplete-dropdown/blob/main/src/AutocompleteDropdownContext.tsx#L114-L130
> 
> This means that if you put the provider at the root level of your app (as recommended by the README), the dropdown list will be mounted all the way at that root level. This means that it will show up underneath the React Native modal.
> 
> One workaround we found was to add another provider inside the modal:
> 
> ```tsx
> <Modal animationType="slide" visible={modalVisible}>
>   <AutocompleteDropdownContextProvider>
>     {children}
>   </AutocompleteDropdownContextProvider>
> </Modal>
> ```
> 
> There are still some minor issues however where the absolute positioning doesn't quite line up with gestures (swipping down on the modal), but it at least shows up.

@navignaw you have to call AutoCompleteDropdownContextProvider outside the modal i.e where you want to put modal (Parent view for modal) then it will work.

**Comment by onmotion** [comment] 2024-01-21 17:22
There is an example https://github.com/onmotion/react-native-autocomplete-dropdown/blob/main/example%2Fcomponents%2FModalExample.tsx

**Comment by p-t10a** [comment] 2024-01-22 00:32
```
例がありますhttps://github.com/onmotion/react-native-autocomplete-dropdown/blob/main/example%2Fcomponents%2FModalExample.tsx
```
I overlooked it. Thanks for the advice.
